apiVersion: serving.knative.dev/v1beta1
kind: Service
metadata:
  name: picalc
  namespace: pipelines-tutorial
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: __IMAGE__
